#!/bin/bash

# FINOVATE ERP X - Deployment Script
# Phase 24: Production Deployment
# Developer: Ahmed Mostafa Ibrahim
# Brand: FINOVATE – AHMED EG

echo "🚀 FINOVATE ERP X - Deployment Script"
echo "======================================"
echo ""

# الألوان
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# التحقق من المتطلبات
check_requirements() {
    echo -e "${BLUE}Checking requirements...${NC}"
    
    # التحقق من Node.js (اختياري للتطوير)
    if command -v node &> /dev/null; then
        echo -e "${GREEN}✓ Node.js installed${NC}"
    else
        echo -e "${YELLOW}⚠ Node.js not found (optional for development)${NC}"
    fi
    
    # التحقق من Python للخادم المحلي
    if command -v python3 &> /dev/null; then
        echo -e "${GREEN}✓ Python3 installed${NC}"
    elif command -v python &> /dev/null; then
        echo -e "${GREEN}✓ Python installed${NC}"
    else
        echo -e "${RED}✗ Python not found - required for local server${NC}"
        exit 1
    fi
    
    echo ""
}

# تحسين الملفات للإنتاج
optimize_files() {
    echo -e "${BLUE}Optimizing files for production...${NC}"
    
    # إنشاء نسخة احتياطية
    if [ -d "./dist" ]; then
        rm -rf ./dist
    fi
    mkdir -p ./dist
    
    # نسخ الملفات الأساسية
    cp -r ./css ./dist/
    cp -r ./js ./dist/
    cp -r ./locales ./dist/
    cp -r ./tests ./dist/
    cp *.html ./dist/
    cp manifest.json ./dist/
    cp sw.js ./dist/
    
    echo -e "${GREEN}✓ Files copied to dist/${NC}"
    
    # ضغط ملفات CSS (إذا كان uglifycss متاحاً)
    if command -v uglifycss &> /dev/null; then
        echo "Compressing CSS files..."
        for file in ./dist/css/*.css; do
            uglifycss "$file" > "${file%.css}.min.css"
        done
        echo -e "${GREEN}✓ CSS files compressed${NC}"
    fi
    
    # ضغط ملفات JS (إذا كان uglifyjs متاحاً)
    if command -v uglifyjs &> /dev/null; then
        echo "Compressing JS files..."
        for file in ./dist/js/*.js; do
            uglifyjs "$file" -c -m > "${file%.js}.min.js"
        done
        echo -e "${GREEN}✓ JS files compressed${NC}"
    fi
    
    echo ""
}

# إعداد Google Apps Script
setup_gas() {
    echo -e "${BLUE}Setting up Google Apps Script...${NC}"
    echo ""
    echo "Instructions for Google Apps Script deployment:"
    echo "1. Go to https://script.google.com"
    echo "2. Create a new project"
    echo "3. Copy the contents of apps-script/ folder"
    echo "4. Deploy as Web App with these settings:"
    echo "   - Execute as: Me"
    echo "   - Who has access: Anyone"
    echo "5. Copy the deployment URL"
    echo "6. Update js/api.js with your URL"
    echo ""
    echo -e "${GREEN}✓ Apps Script folder ready${NC}"
    echo ""
}

# إنشاء ملف التكوين
create_config() {
    echo -e "${BLUE}Creating configuration file...${NC}"
    
    cat > ./dist/config.js << EOF
/**
 * FINOVATE ERP X - Configuration
 * Generated by deploy.sh
 */
const CONFIG = {
    version: '1.0.0',
    buildDate: '$(date -Iseconds)',
    environment: 'production',
    apiEndpoint: 'YOUR_GOOGLE_SCRIPT_URL', // استبدل بالرابط الخاص بك
    features: {
        offlineMode: true,
        notifications: true,
        aiAssistant: true,
        multiLanguage: true,
        multiCurrency: true,
        multiCompany: true
    },
    supportedLanguages: ['ar', 'en', 'fr', 'es', 'de', 'it', 'pt', 'tr', 'ru', 'zh-CN'],
    defaultLanguage: 'ar',
    sessionTimeout: 3600000, // 1 hour
    maxLoginAttempts: 5
};
EOF
    
    echo -e "${GREEN}✓ Configuration file created${NC}"
    echo ""
}

# اختبار النشر
test_deployment() {
    echo -e "${BLUE}Running deployment tests...${NC}"
    
    # التحقق من وجود الملفات الأساسية
    required_files=(
        "./dist/index.html"
        "./dist/login.html"
        "./dist/manifest.json"
        "./dist/sw.js"
        "./dist/css/core.css"
        "./dist/js/app.js"
        "./dist/js/auth.js"
    )
    
    all_exist=true
    for file in "${required_files[@]}"; do
        if [ -f "$file" ]; then
            echo -e "${GREEN}✓ $file exists${NC}"
        else
            echo -e "${RED}✗ $file missing${NC}"
            all_exist=false
        fi
    done
    
    if [ "$all_exist" = true ]; then
        echo -e "${GREEN}✓ All required files present${NC}"
    else
        echo -e "${RED}✗ Some files are missing${NC}"
        return 1
    fi
    
    echo ""
}

# عرض تعليمات التشغيل
show_instructions() {
    echo "======================================"
    echo -e "${GREEN}🎉 Deployment Complete!${NC}"
    echo "======================================"
    echo ""
    echo "Next steps:"
    echo ""
    echo "1. Local Testing:"
    echo "   cd dist && python3 -m http.server 4173"
    echo "   Open: http://localhost:4173"
    echo ""
    echo "2. Google Apps Script Setup:"
    echo "   - Follow instructions above"
    echo "   - Update config.js with your API URL"
    echo ""
    echo "3. PWA Installation:"
    echo "   - Open in Chrome/Edge"
    echo "   - Click install icon in address bar"
    echo ""
    echo "4. Production Hosting Options:"
    echo "   - GitHub Pages (free)"
    echo "   - Netlify (free)"
    echo "   - Vercel (free)"
    echo "   - Your own server"
    echo ""
    echo -e "${YELLOW}Important Notes:${NC}"
    echo "- Remember to set up Google Sheets database"
    echo "- Configure user permissions before going live"
    echo "- Test all modules thoroughly"
    echo "- Set up regular backups"
    echo ""
    echo "Developer: Ahmed Mostafa Ibrahim"
    echo "Brand: FINOVATE – AHMED EG"
    echo "Version: 1.0.0"
    echo ""
}

# التنفيذ الرئيسي
main() {
    check_requirements
    optimize_files
    setup_gas
    create_config
    test_deployment
    show_instructions
}

# تشغيل السكربت
main "$@"
